Blacklist notNull as from Tasty test
There seems to be a missing simplification when compiling from Tasty.
Here is the error message:

```
*** error while checking out/posTestFromTasty/pos/notNull/Test.class after phase readTasty ***
java.lang.AssertionError: assertion failed: Types differ
Original type : (x: Int): Int
After checking: (x: (Int | Null) & NotNull): (Int | Null) & NotNull
Original tree : identity[(Int | Null) & NotNull]
After checking: identity[(Int | Null) & NotNull]
```