Correctly erase Scala 2 intersection types
Because our algorithm for erasing intersection types does not exactly
match the one used by Scala 2, we could end up emitting calls to Scala 2
methods with the wrong bytecode signature, leading to NoSuchMethodError
at runtime. We could try to exactly match what Scala 2 does, but it
turns out that the Scala 2 logic heavily relies on implementation
details which makes it extremely complex to reliably replicate.
Therefore, this commit instead special-cases the erasure of Scala 2
intersections (just like we already special-case the erasure of Java
intersections) and limits which Scala 2 intersection types we support to
a subset that we can erase without too much complications (but even that
still requires ~200 lines of code!). This means that we're now free to
change the way we erase intersections in any way we want without
introducing more compatibility problems (until 3.0.0 that is), I'll
explore this in a follow-up PR.

Fixes #4619. Fixes #9175.